export const jobTitleSearchOptions = [
    'Artificial Intelligence (AI) Engineer',
    'Back-End Developer',
    'Business Analyst',
    'Cloud Solutions Architect',
    'Computer Hardware Engineer',
    'Cybersecurity Analyst',
    'Data Scientist',
    'Database Administrator (DBA)',
    'DevOps Engineer',
    'Front-End Developer',
    'Full-Stack Developer',
    'Game Developer',
    'IT Project Manager',
    'IT Support Specialist',
    'Machine Learning Engineer',
    'Mobile App Developer',
    'Network Administrator',
    'Network Engineer',
    'Product Designer',
    'Quality Assurance (QA) Engineer',
    'Software Engineer',
    'Systems Administrator',
    'Technical Writer',
    'UI/UX Designer',
    'Web Developer',
]

export const jobLocationSearchOptions = [
    'New York, NY',
    'Austin, TX',
    'Boston, MA',
    'Charlotte, NC',
    'Chicago, IL',
    'Columbus, OH',
    'Dallas, TX',
    'Denver, CO',
    'Detroit, MI',
    'El Paso, TX',
    'Fort Worth, TX',
    'Houston, TX',
    'Indianapolis, IN',
    'Jacksonville, FL',
    'Los Angeles, CA',
    'Nashville, TN',
    'Oklahoma City, OK',
    'Philadelphia, PA',
    'Phoenix, AZ',
    'San Antonio, TX',
    'San Diego, CA',
    'San Francisco, CA',
    'San Jose, CA',
    'Seattle, WA',
    'Washington, D.C.',
]