export enum JobLocations {
    NEW_YORK = 'New York, NY',
    AUSTIN = 'Austin, TX',
    BOSTON = 'Boston, MA',
    CHARLOTTE = 'Charlotte, NC',
    CHICAGO = 'Chicago, IL',
    COLUMBUS = 'Columbus, OH',
    DALLAS = 'Dallas, TX',
    DENVER = 'Denver, CO',
    DETROIT = 'Detroit, MI',
    EL_PASO = 'El Paso, TX',
    FORT_WORTH = 'Fort Worth, TX',
    HOUSTON = 'Houston, TX',
    INDIANAPOLIS = 'Indianapolis, IN',
    JACKSONVILLE = 'Jacksonville, FL',
    LOS_ANGELES = 'Los Angeles, CA',
    NASHVILLE = 'Nashville, TN',
    OKLAHOMA_CITY = 'Oklahoma City, OK',
    PHILADELPHIA = 'Philadelphia, PA',
    PHOENIX = 'Phoenix, AZ',
    SAN_ANTONIO = 'San Antonio, TX',
    SAN_DIEGO = 'San Diego, CA',
    SAN_FRANCISCO = 'San Francisco, CA',
    SAN_JOSE = 'San Jose, CA',
    SEATTLE = 'Seattle, WA',
    WASHINGTON_DC = 'Washington, D.C.',
}

export enum JobTitles {
    AI_ENGINEER = 'Artificial Intelligence (AI) Engineer',
    BACK_END_DEVELOPER = 'Back-End Developer',
    BUSINESS_ANALYST = 'Business Analyst',
    CLOUD_SOLUTIONS_ARCHITECT = 'Cloud Solutions Architect',
    COMPUTER_HARDWARE_ENGINEER = 'Computer Hardware Engineer',
    CYBERSECURITY_ANALYST = 'Cybersecurity Analyst',
    DATA_SCIENTIST = 'Data Scientist',
    DATABASE_ADMINISTRATOR = 'Database Administrator (DBA)',
    DEVOPS_ENGINEER = 'DevOps Engineer',
    FRONT_END_DEVELOPER = 'Front-End Developer',
    FULL_STACK_DEVELOPER = 'Full-Stack Developer',
    GAME_DEVELOPER = 'Game Developer',
    IT_PROJECT_MANAGER = 'IT Project Manager',
    IT_SUPPORT_SPECIALIST = 'IT Support Specialist',
    MACHINE_LEARNING_ENGINEER = 'Machine Learning Engineer',
    MOBILE_APP_DEVELOPER = 'Mobile App Developer',
    NETWORK_ADMINISTRATOR = 'Network Administrator',
    NETWORK_ENGINEER = 'Network Engineer',
    PRODUCT_DESIGNER = 'Product Designer',
    QA_ENGINEER = 'Quality Assurance (QA) Engineer',
    SOFTWARE_ENGINEER = 'Software Engineer',
    SYSTEMS_ADMINISTRATOR = 'Systems Administrator',
    TECHNICAL_WRITER = 'Technical Writer',
    UI_UX_DESIGNER = 'UI/UX Designer',
    WEB_DEVELOPER = 'Web Developer',
}
